-- Initial PostgreSQL schema for the deployment RDS database.
-- Run once before starting the application with hibernate.ddl-auto=validate.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS p_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(10) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    profile_image VARCHAR(255),
    role VARCHAR(20) NOT NULL,
    token_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_p_user_username_idx
    ON p_user (username)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_p_user_email_idx
    ON p_user (email)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS p_category (
    category_id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_p_category_name_idx
    ON p_category (name)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_p_category_is_active
    ON p_category (is_active);

CREATE TABLE IF NOT EXISTS p_region (
    region_id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_p_region_name_idx
    ON p_region (name)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_p_region_is_active
    ON p_region (is_active);

CREATE TABLE IF NOT EXISTS p_store (
    store_id UUID PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    category_id UUID NOT NULL,
    region_id UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    phone_number VARCHAR(20) NOT NULL,
    address VARCHAR(255) NOT NULL,
    detail_address VARCHAR(255) NOT NULL,
    min_order_price INTEGER NOT NULL CHECK (min_order_price >= 0),
    delivery_fee INTEGER NOT NULL CHECK (delivery_fee >= 0),
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('OPEN', 'CLOSED', 'BREAK_TIME', 'SUSPENDED', 'PENDING')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    image_url VARCHAR(500),
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT,
    CONSTRAINT fk_p_store_owner
        FOREIGN KEY (owner_id) REFERENCES p_user (user_id),
    CONSTRAINT fk_p_store_category
        FOREIGN KEY (category_id) REFERENCES p_category (category_id),
    CONSTRAINT fk_p_store_region
        FOREIGN KEY (region_id) REFERENCES p_region (region_id)
);

CREATE INDEX IF NOT EXISTS idx_p_store_owner_id ON p_store (owner_id);
CREATE INDEX IF NOT EXISTS idx_p_store_category_id ON p_store (category_id);
CREATE INDEX IF NOT EXISTS idx_p_store_region_id ON p_store (region_id);
CREATE INDEX IF NOT EXISTS idx_p_store_status ON p_store (status);
CREATE INDEX IF NOT EXISTS idx_p_store_is_active ON p_store (is_active);
CREATE INDEX IF NOT EXISTS idx_p_store_name ON p_store (name);

CREATE TABLE IF NOT EXISTS p_address (
    address_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    address_name VARCHAR(50),
    address VARCHAR(255) NOT NULL,
    detail_address VARCHAR(255),
    receiver_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_p_address_user_id ON p_address (user_id);

CREATE TABLE IF NOT EXISTS p_menu (
    menu_id UUID PRIMARY KEY,
    store_id UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    price INTEGER NOT NULL CHECK (price >= 0),
    description TEXT,
    image_url VARCHAR(500),
    display_order INTEGER DEFAULT 0,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    is_sold_out BOOLEAN NOT NULL DEFAULT FALSE,
    is_ai_generated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT,
    CONSTRAINT fk_p_menu_store
        FOREIGN KEY (store_id) REFERENCES p_store (store_id)
);

CREATE INDEX IF NOT EXISTS idx_p_menu_store_id ON p_menu (store_id);

CREATE TABLE IF NOT EXISTS p_cart (
    cart_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_id UUID,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    CONSTRAINT uk_p_cart_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS p_cart_item (
    cart_item_id UUID PRIMARY KEY,
    cart_id UUID NOT NULL,
    menu_id UUID NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    CONSTRAINT fk_p_cart_item_cart
        FOREIGN KEY (cart_id) REFERENCES p_cart (cart_id) ON DELETE CASCADE,
    CONSTRAINT fk_p_cart_item_menu
        FOREIGN KEY (menu_id) REFERENCES p_menu (menu_id),
    CONSTRAINT uk_p_cart_item_cart_menu UNIQUE (cart_id, menu_id)
);

CREATE INDEX IF NOT EXISTS idx_p_cart_item_cart_id ON p_cart_item (cart_id);

CREATE TABLE IF NOT EXISTS p_order (
    order_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_id UUID NOT NULL,
    address_id UUID NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'REQUESTED'
        CHECK (status IN ('REQUESTED', 'ACCEPTED', 'REJECTED', 'COOKING', 'DELIVERING', 'COMPLETED', 'CANCELED')),
    total_menu_price INTEGER NOT NULL CHECK (total_menu_price >= 0),
    delivery_fee INTEGER NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
    discount_price INTEGER NOT NULL DEFAULT 0 CHECK (discount_price >= 0),
    total_price INTEGER NOT NULL CHECK (total_price >= 0),
    delivery_address VARCHAR(255) NOT NULL,
    delivery_detail_address VARCHAR(255),
    delivery_request VARCHAR(255),
    canceled_at TIMESTAMP(6),
    status_reason VARCHAR(255),
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT,
    CONSTRAINT fk_p_order_user
        FOREIGN KEY (user_id) REFERENCES p_user (user_id),
    CONSTRAINT fk_p_order_store
        FOREIGN KEY (store_id) REFERENCES p_store (store_id),
    CONSTRAINT fk_p_order_address
        FOREIGN KEY (address_id) REFERENCES p_address (address_id)
);

CREATE INDEX IF NOT EXISTS idx_p_order_user_id ON p_order (user_id);
CREATE INDEX IF NOT EXISTS idx_p_order_store_id ON p_order (store_id);
CREATE INDEX IF NOT EXISTS idx_p_order_status ON p_order (status);

CREATE TABLE IF NOT EXISTS p_order_item (
    order_item_id UUID PRIMARY KEY,
    order_id UUID NOT NULL,
    menu_id UUID NOT NULL,
    menu_name VARCHAR(100) NOT NULL,
    menu_price INTEGER NOT NULL CHECK (menu_price >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    total_price INTEGER NOT NULL CHECK (total_price >= 0),
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT,
    CONSTRAINT fk_p_order_item_order
        FOREIGN KEY (order_id) REFERENCES p_order (order_id),
    CONSTRAINT fk_p_order_item_menu
        FOREIGN KEY (menu_id) REFERENCES p_menu (menu_id)
);

CREATE INDEX IF NOT EXISTS idx_p_order_item_order_id ON p_order_item (order_id);
CREATE INDEX IF NOT EXISTS idx_p_order_item_menu_id ON p_order_item (menu_id);

CREATE TABLE IF NOT EXISTS p_payment (
    payment_id UUID PRIMARY KEY,
    order_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    payment_method VARCHAR(30) NOT NULL
        CHECK (payment_method IN ('CARD')),
    payment_status VARCHAR(30) NOT NULL
        CHECK (payment_status IN ('PAID', 'CANCELED', 'FAILED')),
    amount INTEGER NOT NULL CHECK (amount >= 0),
    paid_at TIMESTAMP(6),
    canceled_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT,
    CONSTRAINT uk_p_payment_order_id UNIQUE (order_id),
    CONSTRAINT fk_p_payment_order
        FOREIGN KEY (order_id) REFERENCES p_order (order_id),
    CONSTRAINT fk_p_payment_user
        FOREIGN KEY (user_id) REFERENCES p_user (user_id)
);

CREATE INDEX IF NOT EXISTS idx_p_payment_user_id ON p_payment (user_id);

CREATE TABLE IF NOT EXISTS p_review (
    review_id UUID PRIMARY KEY,
    order_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    store_id UUID NOT NULL,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content VARCHAR(1000) NOT NULL,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT,
    CONSTRAINT uk_p_review_order_id UNIQUE (order_id),
    CONSTRAINT fk_p_review_order
        FOREIGN KEY (order_id) REFERENCES p_order (order_id),
    CONSTRAINT fk_p_review_user
        FOREIGN KEY (user_id) REFERENCES p_user (user_id),
    CONSTRAINT fk_p_review_store
        FOREIGN KEY (store_id) REFERENCES p_store (store_id)
);

CREATE INDEX IF NOT EXISTS idx_p_review_store_id ON p_review (store_id);
CREATE INDEX IF NOT EXISTS idx_p_review_user_id ON p_review (user_id);

CREATE TABLE IF NOT EXISTS p_ai_request (
    ai_request_id UUID PRIMARY KEY,
    menu_id UUID,
    store_id UUID,
    user_id BIGINT NOT NULL,
    prompt TEXT NOT NULL,
    final_prompt TEXT,
    response_content TEXT,
    ai_model VARCHAR(50),
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('SUCCESS', 'FAILED')),
    created_at TIMESTAMP(6),
    created_by BIGINT,
    CONSTRAINT fk_p_ai_request_menu
        FOREIGN KEY (menu_id) REFERENCES p_menu (menu_id),
    CONSTRAINT fk_p_ai_request_store
        FOREIGN KEY (store_id) REFERENCES p_store (store_id),
    CONSTRAINT fk_p_ai_request_user
        FOREIGN KEY (user_id) REFERENCES p_user (user_id)
);

CREATE INDEX IF NOT EXISTS idx_p_ai_request_menu_id ON p_ai_request (menu_id);
CREATE INDEX IF NOT EXISTS idx_p_ai_request_user_id ON p_ai_request (user_id);
