spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:delivery_db}
    username: ${POSTGRES_USER:found404}
    password: ${POSTGRES_PASSWORD:found404}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

aws:
  s3:
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-flash-lite-latest
  base-url: https://generativelanguage.googleapis.com/v1beta