-- p_user: 사용자 계정 테이블

CREATE TABLE IF NOT EXISTS p_user (

                                      user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                      username VARCHAR(10) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    profile_image VARCHAR(255),
    role VARCHAR(20) NOT NULL,
    token_version BIGINT NOT NULL DEFAULT 0,

    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT
    );

-- username 중복 가입 방지 (탈퇴(Soft Delete)한 계정은 제외 — 탈퇴 후 동일 username/email로 재가입 허용)
-- partial unique index: deleted_at이 NULL인(탈퇴 안 한) 행끼리만 유니크 제약이 걸린다.
CREATE UNIQUE INDEX IF NOT EXISTS uk_p_user_username_idx
    ON p_user (username) WHERE deleted_at IS NULL;
-- email 중복 가입 방지 (탈퇴한 계정 제외)
CREATE UNIQUE INDEX IF NOT EXISTS uk_p_user_email_idx
    ON p_user (email) WHERE deleted_at IS NULL;