-- p_user: 사용자 계정 테이블

CREATE TABLE IF NOT EXISTS p_user (

    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(10) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    profile_image VARCHAR(255),
    role VARCHAR(20) NOT NULL,

    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    deleted_at TIMESTAMP(6),
    deleted_by BIGINT
    );

-- username 중복 가입 방지 (Soft Delete 대상 포함 전체 유니크)
CREATE UNIQUE INDEX IF NOT EXISTS uk_p_user_username_idx
    ON p_user (username);
-- email 중복 가입 방지
CREATE UNIQUE INDEX IF NOT EXISTS uk_p_user_email_idx
    ON p_user (email);